#!/bin/bash
mysql -u root -proot -e "CREATE DATABASE USERS_DB;"
mysql -u root -proot -e "USE USERS_DB; CREATE TABLE Users (username VARCHAR(50), password VARCHAR(255));"
for i in {1..10}; do
    user="user$i"
    db="database$i"
    password=$(openssl rand -base64 5 | tr -d '=+/')
    short_password=$(echo "$password" | cut -c 1-5)
    
    mysql -u root -proot -e "CREATE DATABASE $db;"
    mysql -u root -proot -e "CREATE USER '$user'@'localhost' IDENTIFIED BY '$short_password';"
    mysql -u root -proot -e "GRANT ALL PRIVILEGES ON $db.* TO '$user'@'localhost';"
    mysql -u root -proot -e "USE USERS_DB; INSERT INTO Users (username, password) VALUES ('$user', '$short_password');"
done


